// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthSvc is a mock of AuthSvc interface.
type MockAuthSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAuthSvcMockRecorder
	isgomock struct{}
}

// MockAuthSvcMockRecorder is the mock recorder for MockAuthSvc.
type MockAuthSvcMockRecorder struct {
	mock *MockAuthSvc
}

// NewMockAuthSvc creates a new mock instance.
func NewMockAuthSvc(ctrl *gomock.Controller) *MockAuthSvc {
	mock := &MockAuthSvc{ctrl: ctrl}
	mock.recorder = &MockAuthSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthSvc) EXPECT() *MockAuthSvcMockRecorder {
	return m.recorder
}

// AuthenticateGoogle mocks base method.
func (m *MockAuthSvc) AuthenticateGoogle(ctx context.Context, code, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateGoogle", ctx, code, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateGoogle indicates an expected call of AuthenticateGoogle.
func (mr *MockAuthSvcMockRecorder) AuthenticateGoogle(ctx, code, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateGoogle", reflect.TypeOf((*MockAuthSvc)(nil).AuthenticateGoogle), ctx, code, state)
}

// GetGoogleRedirectURL mocks base method.
func (m *MockAuthSvc) GetGoogleRedirectURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoogleRedirectURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoogleRedirectURL indicates an expected call of GetGoogleRedirectURL.
func (mr *MockAuthSvcMockRecorder) GetGoogleRedirectURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoogleRedirectURL", reflect.TypeOf((*MockAuthSvc)(nil).GetGoogleRedirectURL), ctx)
}

// Logout mocks base method.
func (m *MockAuthSvc) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthSvcMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthSvc)(nil).Logout), ctx, sessionID)
}
