services:
  mixo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro

  postgres:
    container_name: mixo-postgres
    image: "postgres:18.4-alpine3.23"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql