// Code generated by MockGen. DO NOT EDIT.
// Source: google.go
//
// Generated by this command:
//
//	mockgen -source=google.go -destination=mocks/google_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	idtoken "google.golang.org/api/idtoken"
)

// MockIDTokenValidator is a mock of IDTokenValidator interface.
type MockIDTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIDTokenValidatorMockRecorder
	isgomock struct{}
}

// MockIDTokenValidatorMockRecorder is the mock recorder for MockIDTokenValidator.
type MockIDTokenValidatorMockRecorder struct {
	mock *MockIDTokenValidator
}

// NewMockIDTokenValidator creates a new mock instance.
func NewMockIDTokenValidator(ctrl *gomock.Controller) *MockIDTokenValidator {
	mock := &MockIDTokenValidator{ctrl: ctrl}
	mock.recorder = &MockIDTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDTokenValidator) EXPECT() *MockIDTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockIDTokenValidator) Validate(ctx context.Context, token, audience string) (*idtoken.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token, audience)
	ret0, _ := ret[0].(*idtoken.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockIDTokenValidatorMockRecorder) Validate(ctx, token, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIDTokenValidator)(nil).Validate), ctx, token, audience)
}
