// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source=session.go -destination=mock_session_test.go -package=session
//

// Package session is a generated GoMock package.
package session

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/kcansari/mixo/internal/domain"
	security "github.com/kcansari/mixo/internal/security"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTSvc is a mock of JWTSvc interface.
type MockJWTSvc struct {
	ctrl     *gomock.Controller
	recorder *MockJWTSvcMockRecorder
	isgomock struct{}
}

// MockJWTSvcMockRecorder is the mock recorder for MockJWTSvc.
type MockJWTSvcMockRecorder struct {
	mock *MockJWTSvc
}

// NewMockJWTSvc creates a new mock instance.
func NewMockJWTSvc(ctrl *gomock.Controller) *MockJWTSvc {
	mock := &MockJWTSvc{ctrl: ctrl}
	mock.recorder = &MockJWTSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTSvc) EXPECT() *MockJWTSvcMockRecorder {
	return m.recorder
}

// GenerateJWT mocks base method.
func (m *MockJWTSvc) GenerateJWT(userID uuid.UUID, exp time.Time, tokenType security.TokenType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", userID, exp, tokenType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockJWTSvcMockRecorder) GenerateJWT(userID, exp, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockJWTSvc)(nil).GenerateJWT), userID, exp, tokenType)
}

// ParseJWT mocks base method.
func (m *MockJWTSvc) ParseJWT(t string) (*security.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseJWT", t)
	ret0, _ := ret[0].(*security.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseJWT indicates an expected call of ParseJWT.
func (mr *MockJWTSvcMockRecorder) ParseJWT(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseJWT", reflect.TypeOf((*MockJWTSvc)(nil).ParseJWT), t)
}

// MockTokenStore is a mock of TokenStore interface.
type MockTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockTokenStoreMockRecorder
	isgomock struct{}
}

// MockTokenStoreMockRecorder is the mock recorder for MockTokenStore.
type MockTokenStoreMockRecorder struct {
	mock *MockTokenStore
}

// NewMockTokenStore creates a new mock instance.
func NewMockTokenStore(ctrl *gomock.Controller) *MockTokenStore {
	mock := &MockTokenStore{ctrl: ctrl}
	mock.recorder = &MockTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenStore) EXPECT() *MockTokenStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTokenStore) Create(ctx context.Context, refreshToken string, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, refreshToken, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTokenStoreMockRecorder) Create(ctx, refreshToken, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTokenStore)(nil).Create), ctx, refreshToken, userID)
}

// GetByTokenHash mocks base method.
func (m *MockTokenStore) GetByTokenHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockTokenStoreMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockTokenStore)(nil).GetByTokenHash), ctx, tokenHash)
}

// GetByUserID mocks base method.
func (m *MockTokenStore) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockTokenStoreMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockTokenStore)(nil).GetByUserID), ctx, userID)
}

// Revoke mocks base method.
func (m *MockTokenStore) Revoke(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenStoreMockRecorder) Revoke(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenStore)(nil).Revoke), ctx, userID)
}

// MockHMACSvc is a mock of HMACSvc interface.
type MockHMACSvc struct {
	ctrl     *gomock.Controller
	recorder *MockHMACSvcMockRecorder
	isgomock struct{}
}

// MockHMACSvcMockRecorder is the mock recorder for MockHMACSvc.
type MockHMACSvcMockRecorder struct {
	mock *MockHMACSvc
}

// NewMockHMACSvc creates a new mock instance.
func NewMockHMACSvc(ctrl *gomock.Controller) *MockHMACSvc {
	mock := &MockHMACSvc{ctrl: ctrl}
	mock.recorder = &MockHMACSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHMACSvc) EXPECT() *MockHMACSvcMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *MockHMACSvc) Sign(data string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// Sign indicates an expected call of Sign.
func (mr *MockHMACSvcMockRecorder) Sign(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockHMACSvc)(nil).Sign), data)
}
