// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kcansari/mixo/ent/predicate"
	"github.com/kcansari/mixo/ent/refresh_token"
	"github.com/kcansari/mixo/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetVerifiedEmail sets the "verified_email" field.
func (_u *UserUpdate) SetVerifiedEmail(v bool) *UserUpdate {
	_u.mutation.SetVerifiedEmail(v)
	return _u
}

// SetNillableVerifiedEmail sets the "verified_email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableVerifiedEmail(v *bool) *UserUpdate {
	if v != nil {
		_u.SetVerifiedEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *UserUpdate) SetGivenName(v string) *UserUpdate {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGivenName(v *string) *UserUpdate {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// SetFamilyName sets the "family_name" field.
func (_u *UserUpdate) SetFamilyName(v string) *UserUpdate {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "family_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFamilyName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *UserUpdate) SetPicture(v string) *UserUpdate {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePicture(v *string) *UserUpdate {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserUpdate) SetProviderUserID(v string) *UserUpdate {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableProviderUserID(v *string) *UserUpdate {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserUpdate) SetRefreshToken(v string) *UserUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRefreshToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserUpdate) ClearRefreshToken() *UserUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserUpdate) SetProvider(v string) *UserUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserUpdate) SetNillableProvider(v *string) *UserUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdate) SetIsAdmin(v bool) *UserUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsAdmin(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// AddRefreshTokenIDs adds the "refresh_tokens" edge to the Refresh_Token entity by IDs.
func (_u *UserUpdate) AddRefreshTokenIDs(ids ...int) *UserUpdate {
	_u.mutation.AddRefreshTokenIDs(ids...)
	return _u
}

// AddRefreshTokens adds the "refresh_tokens" edges to the Refresh_Token entity.
func (_u *UserUpdate) AddRefreshTokens(v ...*Refresh_Token) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshTokenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRefreshTokens clears all "refresh_tokens" edges to the Refresh_Token entity.
func (_u *UserUpdate) ClearRefreshTokens() *UserUpdate {
	_u.mutation.ClearRefreshTokens()
	return _u
}

// RemoveRefreshTokenIDs removes the "refresh_tokens" edge to Refresh_Token entities by IDs.
func (_u *UserUpdate) RemoveRefreshTokenIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveRefreshTokenIDs(ids...)
	return _u
}

// RemoveRefreshTokens removes "refresh_tokens" edges to Refresh_Token entities.
func (_u *UserUpdate) RemoveRefreshTokens(v ...*Refresh_Token) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedEmail(); ok {
		_spec.SetField(user.FieldVerifiedEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(user.FieldGivenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(user.FieldFamilyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(user.FieldPicture, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(user.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(user.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(user.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(user.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if _u.mutation.RefreshTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshTokensIDs(); len(nodes) > 0 && !_u.mutation.RefreshTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetVerifiedEmail sets the "verified_email" field.
func (_u *UserUpdateOne) SetVerifiedEmail(v bool) *UserUpdateOne {
	_u.mutation.SetVerifiedEmail(v)
	return _u
}

// SetNillableVerifiedEmail sets the "verified_email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableVerifiedEmail(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetVerifiedEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *UserUpdateOne) SetGivenName(v string) *UserUpdateOne {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGivenName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// SetFamilyName sets the "family_name" field.
func (_u *UserUpdateOne) SetFamilyName(v string) *UserUpdateOne {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "family_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFamilyName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *UserUpdateOne) SetPicture(v string) *UserUpdateOne {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePicture(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserUpdateOne) SetProviderUserID(v string) *UserUpdateOne {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableProviderUserID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserUpdateOne) SetRefreshToken(v string) *UserUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRefreshToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserUpdateOne) ClearRefreshToken() *UserUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserUpdateOne) SetProvider(v string) *UserUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableProvider(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdateOne) SetIsAdmin(v bool) *UserUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsAdmin(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// AddRefreshTokenIDs adds the "refresh_tokens" edge to the Refresh_Token entity by IDs.
func (_u *UserUpdateOne) AddRefreshTokenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddRefreshTokenIDs(ids...)
	return _u
}

// AddRefreshTokens adds the "refresh_tokens" edges to the Refresh_Token entity.
func (_u *UserUpdateOne) AddRefreshTokens(v ...*Refresh_Token) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshTokenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRefreshTokens clears all "refresh_tokens" edges to the Refresh_Token entity.
func (_u *UserUpdateOne) ClearRefreshTokens() *UserUpdateOne {
	_u.mutation.ClearRefreshTokens()
	return _u
}

// RemoveRefreshTokenIDs removes the "refresh_tokens" edge to Refresh_Token entities by IDs.
func (_u *UserUpdateOne) RemoveRefreshTokenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveRefreshTokenIDs(ids...)
	return _u
}

// RemoveRefreshTokens removes "refresh_tokens" edges to Refresh_Token entities.
func (_u *UserUpdateOne) RemoveRefreshTokens(v ...*Refresh_Token) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshTokenIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedEmail(); ok {
		_spec.SetField(user.FieldVerifiedEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(user.FieldGivenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(user.FieldFamilyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(user.FieldPicture, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(user.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(user.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(user.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(user.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if _u.mutation.RefreshTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshTokensIDs(); len(nodes) > 0 && !_u.mutation.RefreshTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshTokensTable,
			Columns: []string{user.RefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refresh_token.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
