// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kcansari/mixo/internal/domain"
	oauth "github.com/kcansari/mixo/internal/oauth"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthGoogle is a mock of OAuthGoogle interface.
type MockOAuthGoogle struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthGoogleMockRecorder
	isgomock struct{}
}

// MockOAuthGoogleMockRecorder is the mock recorder for MockOAuthGoogle.
type MockOAuthGoogleMockRecorder struct {
	mock *MockOAuthGoogle
}

// NewMockOAuthGoogle creates a new mock instance.
func NewMockOAuthGoogle(ctrl *gomock.Controller) *MockOAuthGoogle {
	mock := &MockOAuthGoogle{ctrl: ctrl}
	mock.recorder = &MockOAuthGoogleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthGoogle) EXPECT() *MockOAuthGoogleMockRecorder {
	return m.recorder
}

// VerifyIDToken mocks base method.
func (m *MockOAuthGoogle) VerifyIDToken(ctx context.Context, token string) (*oauth.GoogleUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, token)
	ret0, _ := ret[0].(*oauth.GoogleUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockOAuthGoogleMockRecorder) VerifyIDToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockOAuthGoogle)(nil).VerifyIDToken), ctx, token)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionManager) Create(ctx context.Context, userID uuid.UUID) (domain.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(domain.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionManagerMockRecorder) Create(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionManager)(nil).Create), ctx, userID)
}

// Destroy mocks base method.
func (m *MockSessionManager) Destroy(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockSessionManagerMockRecorder) Destroy(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockSessionManager)(nil).Destroy), ctx, userID)
}

// MockAuthUserStore is a mock of AuthUserStore interface.
type MockAuthUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUserStoreMockRecorder
	isgomock struct{}
}

// MockAuthUserStoreMockRecorder is the mock recorder for MockAuthUserStore.
type MockAuthUserStoreMockRecorder struct {
	mock *MockAuthUserStore
}

// NewMockAuthUserStore creates a new mock instance.
func NewMockAuthUserStore(ctrl *gomock.Controller) *MockAuthUserStore {
	mock := &MockAuthUserStore{ctrl: ctrl}
	mock.recorder = &MockAuthUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUserStore) EXPECT() *MockAuthUserStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthUserStore) Create(ctx context.Context, user domain.UserCreate) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthUserStoreMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthUserStore)(nil).Create), ctx, user)
}

// GetByProviderUserID mocks base method.
func (m *MockAuthUserStore) GetByProviderUserID(ctx context.Context, providerUserID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProviderUserID", ctx, providerUserID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProviderUserID indicates an expected call of GetByProviderUserID.
func (mr *MockAuthUserStoreMockRecorder) GetByProviderUserID(ctx, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProviderUserID", reflect.TypeOf((*MockAuthUserStore)(nil).GetByProviderUserID), ctx, providerUserID)
}
