// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kcansari/mixo/internal/domain"
	session "github.com/kcansari/mixo/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionManager) Create(ctx context.Context, userID uuid.UUID) (domain.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(domain.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionManagerMockRecorder) Create(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionManager)(nil).Create), ctx, userID)
}

// Destroy mocks base method.
func (m *MockSessionManager) Destroy(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockSessionManagerMockRecorder) Destroy(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockSessionManager)(nil).Destroy), ctx, userID)
}

// GetAccessToken mocks base method.
func (m *MockSessionManager) GetAccessToken(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockSessionManagerMockRecorder) GetAccessToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockSessionManager)(nil).GetAccessToken), ctx, refreshToken)
}

// GetInfo mocks base method.
func (m *MockSessionManager) GetInfo(tokenString string) (session.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", tokenString)
	ret0, _ := ret[0].(session.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockSessionManagerMockRecorder) GetInfo(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockSessionManager)(nil).GetInfo), tokenString)
}

// GetRefreshToken mocks base method.
func (m *MockSessionManager) GetRefreshToken(ctx context.Context, userID uuid.UUID) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, userID)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockSessionManagerMockRecorder) GetRefreshToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockSessionManager)(nil).GetRefreshToken), ctx, userID)
}

// IsValidRefreshToken mocks base method.
func (m *MockSessionManager) IsValidRefreshToken(ctx context.Context, refreshToken string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidRefreshToken indicates an expected call of IsValidRefreshToken.
func (mr *MockSessionManagerMockRecorder) IsValidRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidRefreshToken", reflect.TypeOf((*MockSessionManager)(nil).IsValidRefreshToken), ctx, refreshToken)
}

// MockJWTSvc is a mock of JWTSvc interface.
type MockJWTSvc struct {
	ctrl     *gomock.Controller
	recorder *MockJWTSvcMockRecorder
	isgomock struct{}
}

// MockJWTSvcMockRecorder is the mock recorder for MockJWTSvc.
type MockJWTSvcMockRecorder struct {
	mock *MockJWTSvc
}

// NewMockJWTSvc creates a new mock instance.
func NewMockJWTSvc(ctrl *gomock.Controller) *MockJWTSvc {
	mock := &MockJWTSvc{ctrl: ctrl}
	mock.recorder = &MockJWTSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTSvc) EXPECT() *MockJWTSvcMockRecorder {
	return m.recorder
}

// ExtractBearerToken mocks base method.
func (m *MockJWTSvc) ExtractBearerToken(req *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractBearerToken", req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractBearerToken indicates an expected call of ExtractBearerToken.
func (mr *MockJWTSvcMockRecorder) ExtractBearerToken(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractBearerToken", reflect.TypeOf((*MockJWTSvc)(nil).ExtractBearerToken), req)
}
